pipeline {
  agent {
    node {
      label 'DockerVM'
    }
    
  }
  stages {
    stage('Pull down config files') {
      steps {
        echo 'Grabbing Config Files from server'
        sh '''scp mclinx:~/fpcConfigTest/fpcConfigTest.tgz . || echo "archive not found... proceeding"
scp mclinx:~/fpcConfigTest/test_ipaddr.py . || echo "could not retrieve test suite"
scp -3 mclinx:~/fpcConfigTest/test_vlan_position_in_fpcConfig_file.sh s27app:~/fpcConfigTest/ || echo "could not copy testfile"
'''
      }
    }
    stage('Execute Testcase Too') {
      steps {
        sh '''echo "=========================================================="
echo "[###] Execute testcase on remote appliance (via SSH) [###]"
echo "=========================================================="

ssh s27app "cd /root/fpcConfigTest; ./test_vlan_position_in_fpcConfig_file.sh"
'''
      }
    }
    stage('Collect Output Files') {
      steps {
        ws(dir: 'TestOutputFiles') {
          sh '''echo "==================================================="
echo "[###] The test generates some output files.         "
echo "      Zip them up and copy them to workspace: [###]"
echo "==================================================="

ssh s27app "cd /root/fpcConfigTest/test_output; tar -cvf ../fpc_config_test_results.tgz ."
scp s27app:/root/fpcConfigTest/fpc_config_test_results.tgz .
'''
          sh '''# Extract files from the archive
tar -xvf fpc_config_test_results.tgz'''
        }
        
      }
    }
    stage('Run Tests') {
      steps {
        sh '''echo "==================================================="
echo "[###] Preparing to run testsuite [###]"
echo "==================================================="

# Test all of the files generated by our test by cycling
# through all of the files in the output directoy
for ipaddr_file in ipaddr_output/*; do
	python test_ipaddr.py $ipaddr_file >> netcard_verification_results.txt
    echo "" >> netcard_verification_results.txt
done

cat netcard_verification_results.txt
echo ""'''
      }
    }
    stage('End') {
      steps {
        echo 'Process Complete'
      }
    }
  }
}